name = "testcontainers_gleam"
version = "1.0.1"
description = "Gleam TestContainers wrapper around Elixir TestContainers"
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "testcontainers-gleam" }
gleam = ">= 1.2.0"

[dependencies]
gleam_erlang = ">= 0.25.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
testcontainers = ">= 1.8.1"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
